include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    deprecated_member_use: ignore
    library_private_types_in_public_api: ignore
    prefer_const_constructors: ignore
    prefer_interpolation_to_compose_strings: ignore
    use_build_context_synchronously: ignore
