name: dlaf_edu_app
description: "Proyecto hecho en flutter para el aprendizaje y traducción de lenguaje de señas"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.7.0
  flutter_svg: ^2.0.15
  firebase_auth: ^5.3.3
  syncfusion_flutter_pdfviewer: ^27.2.4
  cloud_firestore: ^5.5.0
  # camera: ^0.10.4
  # camera_android_camerax: ^0.6.10
  # image: ^3.3.0  
  # tflite_flutter_helper: ^0.2.1
  # tflite_flutter: ^0.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/videos/
    - assets/models/
  
  fonts:
    - family: Montserrat
      fonts: 
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600