// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYSPfykAXsDLFmrSjc4GOm9lHHl32ve1k',
    appId: '1:148866572482:web:8a65756156371dbefbdb5b',
    messagingSenderId: '148866572482',
    projectId: 'dlaf-edu',
    authDomain: 'dlaf-edu.firebaseapp.com',
    storageBucket: 'dlaf-edu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsQqoy84Fy5_gaHF3orX4uRWTUPY_S-FI',
    appId: '1:148866572482:android:53887b73fcd4efeafbdb5b',
    messagingSenderId: '148866572482',
    projectId: 'dlaf-edu',
    storageBucket: 'dlaf-edu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC2SoGCWdzsOspOFq0GgVSzrJcJRBlS-g',
    appId: '1:148866572482:ios:cfc0698dd7fea15bfbdb5b',
    messagingSenderId: '148866572482',
    projectId: 'dlaf-edu',
    storageBucket: 'dlaf-edu.firebasestorage.app',
    iosBundleId: 'com.dlafedu.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC2SoGCWdzsOspOFq0GgVSzrJcJRBlS-g',
    appId: '1:148866572482:ios:ba73ef8c6835288cfbdb5b',
    messagingSenderId: '148866572482',
    projectId: 'dlaf-edu',
    storageBucket: 'dlaf-edu.firebasestorage.app',
    iosBundleId: 'com.example.dlafEduApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYSPfykAXsDLFmrSjc4GOm9lHHl32ve1k',
    appId: '1:148866572482:web:a823a9330729904ffbdb5b',
    messagingSenderId: '148866572482',
    projectId: 'dlaf-edu',
    authDomain: 'dlaf-edu.firebaseapp.com',
    storageBucket: 'dlaf-edu.firebasestorage.app',
  );

}